setting_name: CHESS_IR_CG_UT

# System settings
num_workers: 5

# Chat-specific settings
enable_chat: true
chat_settings:
  memory:
    window_size: 10
    relevance_threshold: 0.7
  context:
    max_history_messages: 50
    include_sql_history: true
  response:
    style: conversational
    include_context: true



team_agents:
  chat_context_analyzer:
    engine: 'gpt-4o-mini'
    tools:
      history_analyzer:
        template_name: 'history_analyzer_wtl'
        engine_config:
          engine_name: 'gpt-4o-mini'
          temperature: 0.0
        parser_name: 'query_enhancement'
      query_enhancement:
        template_name: 'query_enhancement_wtl'
        engine_config:
          engine_name: 'gpt-4o-mini'
          temperature: 0.0
        parser_name: 'query_enhancement'
        
  information_retriever:
    engine: 'gpt-4o-mini'
    tools:
      extract_keywords:
        template_name: 'extract_keywords'
        engine_config:
          engine_name: 'gpt-4o-mini'
          temperature: 0.2
        parser_name: 'python_list_output_parser'
      retrieve_entity: {}
      retrieve_context:
        top_k: 5

  candidate_generator:
    engine: 'gemini-2.0-flash-exp'
    tools:
      generate_candidate:
        generator_configs:
          - template_name: 'generate_candidate_wtl'
            engine_config:
              engine_name: 'gemini-2.0-flash-exp'
              temperature: 0.1
            parser_name: 'generate_candidate_gemini_markdown_cot'
            sampling_count: 7
          - template_name: 'generate_candidate_wtl_two'
            engine_config:
              engine_name: 'gemini-2.0-flash-exp'
              temperature: 0.1
            parser_name: 'generate_candidate_gemini_markdown_cot'
            sampling_count: 7

      revise:
        template_name: 'revise_one'
        engine_config:
          engine_name: 'gpt-4o-mini'
          temperature: 0.0
        parser_name: 'revise_new'
  
  sql_executor:
    engine: 'gpt-4o-mini'
    tools: {}  # Simple config as the executor doesn't need special settings  
    
  response_generator:
    engine: 'gpt-4o-mini'
    tools:
      generate_response:
        template_name: 'response_generation'
        engine_config:
          engine_name: 'gpt-4o-mini'
          temperature: 0.0
        parser_name: 'response_generation'

  unit_tester:
    engine: 'gpt-4o-mini'
    tools:
      generate_unit_test:
        template_name: 'generate_unit_tests'
        engine_config:
          engine_name: 'gpt-4o-mini'
          temperature: 0.8
        parser_name: 'generate_unit_tests'
        unit_test_count: 5
        sampling_count: 1

      evaluate:
        template_name: 'evaluate'
        engine_config:
          engine_name: 'gpt-4o-mini'
          temperature: 0.0
        parser_name: 'evaluate'